spring.application.name=Smart Healthcare Platform

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Kien@1109AA.

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

# Tat luu phien lam viec khi server restart - chi Remember-Me moi giu dang nhap
server.servlet.session.persistent=false